"""`sdlc adapters sync`: generate thin per-tool entry points from one source.

AGENTS.md is the universal file (read natively by Codex, Cursor, Copilot, Aider,
Zed, Jules and many others). Tools with their own format get a pointer to it, and
tools with slash commands get one per play that defers to `sdlc prompt`.
"""
from __future__ import annotations

from pathlib import Path

from .config import KIT_ROOT, Config

MARK = "generated by `sdlc adapters sync`; edit the kit or sdlc.toml, not this file"
PLAYS = ("intent", "design", "architect", "ticketize", "build", "test", "review", "observe", "research")
TICKET_PLAYS = ("build", "test", "review")


def _cmd_body(play: str, arg: str) -> str:
    target = f"{play} {arg}" if play in TICKET_PLAYS else play
    return (f"Run `sdlc prompt {target}` in a shell. It prints the path of a generated prompt file.\n"
            "Read that file completely and follow it exactly; it is your whole task.\n")


def files(cfg: Config) -> dict[str, str]:
    out: dict[str, str] = {}
    tools = cfg.section("adapters").get("tools", ["claude", "cursor", "copilot", "gemini"])
    pointer = (f"<!-- {MARK} -->\n"
               "Read and obey `AGENTS.md` at the repository root before doing anything.\n")
    if "claude" in tools:
        out["CLAUDE.md"] = f"<!-- {MARK} -->\n@AGENTS.md\n"
        for p in PLAYS:
            out[f".claude/commands/sdlc-{p}.md"] = (
                f"---\ndescription: ai-sdlc kit play {p}\n---\n<!-- {MARK} -->\n" + _cmd_body(p, "$ARGUMENTS"))
    if "gemini" in tools:
        out["GEMINI.md"] = f"<!-- {MARK} -->\n@AGENTS.md\n"
    if "cursor" in tools:
        out[".cursor/rules/sdlc.mdc"] = ("---\ndescription: ai-sdlc kit operating rules\nalwaysApply: true\n---\n"
                                         f"<!-- {MARK} -->\n@AGENTS.md\n")
    if "copilot" in tools:
        out[".github/copilot-instructions.md"] = pointer
    return out


def sync(cfg: Config, check: bool = False) -> list[str]:
    """Write (or with check=True, compare) generated files. Returns paths that differ."""
    stale = []
    for rel, content in files(cfg).items():
        p = cfg.root / rel
        cur = p.read_text(encoding="utf-8") if p.is_file() else None
        if cur == content:
            continue
        if cur is not None and MARK not in cur:
            stale.append(f"{rel} (hand-written; not overwritten)")
            continue
        stale.append(rel)
        if not check:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content, encoding="utf-8")
    return stale


def product_agents_md(cfg: Config) -> str:
    return (KIT_ROOT / "templates" / "product-AGENTS.md").read_text(encoding="utf-8")
