"""`sdlc prompt <play> [ticket]`: assemble the exact context a play needs.

Every agent gets the same bytes for the same inputs: the play skill, the ticket,
the cited requirements and contract sections, the skills the ticket lists, the
write set, and the definition of done. Nothing is left for the agent to go find.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from . import fm, gitutil, skills
from .artifacts import Repo, Ticket
from .config import KIT_ROOT, Config

TICKET_PLAYS = ("build", "test", "review")
LEAD_PLAYS = {
    "intent": ("templates/intent.md",),
    "design": ("templates/spec.md", "templates/page.md"),
    "architect": ("templates/plan.md", "templates/CONTRACTS.md", "templates/adr.md"),
    "ticketize": ("templates/ticket.md",),
    "observe": ("templates/incident.md", "templates/intent.md"),
    "research": (),
}


def render(cfg: Config, play: str, ticket_id: str | None = None, feedback: str = "",
           extra: str = "") -> str:
    repo = Repo(cfg)
    parts: list[str] = []
    title = f"{play.upper()} {ticket_id or ''}".strip()
    parts.append(f"# sdlc play: {title}\n\n<!-- generated by `sdlc prompt`; regenerate, do not edit -->\n")
    parts.append(_section("Operating rules", _body(KIT_ROOT / "AGENTS.md")))
    parts.append(_section(f"Play skill: {play}", _body(KIT_ROOT / "skills" / play / "SKILL.md")))
    if play in TICKET_PLAYS:
        if not ticket_id:
            raise SystemExit(f"{play} needs a ticket id")
        t = repo.ticket(ticket_id)
        parts.extend(_ticket_context(cfg, repo, t, play))
    elif play in LEAD_PLAYS:
        for tpl in LEAD_PLAYS[play]:
            p = KIT_ROOT / tpl
            if p.is_file():
                parts.append(_section(f"Template: {tpl}", "```markdown\n" + p.read_text(encoding="utf-8").rstrip() + "\n```"))
        parts.append(_section("Upstream artifacts in this repo", _inventory(cfg)))
    else:
        raise SystemExit(f"unknown play {play!r}")
    if extra:
        parts.append(_section("Lead instructions for this run", extra))
    if feedback:
        parts.append(_section("The previous attempt failed the gate. Fix exactly this", feedback))
    return "\n".join(parts).rstrip() + "\n"


def _ticket_context(cfg: Config, repo: Repo, t: Ticket, play: str) -> list[str]:
    out = [_section(f"Ticket {t.id} ({cfg.rel(t.path)})", "```markdown\n" + t.path.read_text(encoding="utf-8").rstrip() + "\n```")]
    reqs = repo.requirements()
    lines = [f"- **{r}** {reqs[r].text}" if r in reqs else f"- **{r}** (not found in any spec)" for r in t.requirements]
    if lines:
        out.append(_section("Requirements this ticket serves", "\n".join(lines)))
    out.append(_section("Contracts this ticket must honour", _contract_excerpt(cfg, repo, t)))
    shared = _shared_modules(cfg, t)
    if shared:
        out.append(_section("Shared modules (import these; never re-implement them)", shared))
    if t.type in ("frontend", "fullstack"):
        out.extend(_design_context(cfg, repo, t))
    for s in t.skills:
        # The prompt already carries its own play skill; another play's would contradict it
        # (a ticket listing `build` put build's instructions into the test play).
        if s in TICKET_PLAYS:
            continue
        p = skills.resolve(cfg, s)
        if p is not None:
            out.append(_section(f"Skill: {s}", _body(p)))
    title = ("Write set (areas: the gate flags other files for the reviewer)" if play == "build"
             else "Write set (the gate rejects anything else)")
    out.append(_section(title, _write_set(cfg, t, play)))
    if play == "review":
        out.append(_section("Evidence (build, test) and the diff", _evidence(cfg, t)))
    out.append(_section("Definition of done", _dod(cfg, t, play)))
    return out


def _contract_excerpt(cfg: Config, repo: Repo, t: Ticket) -> str:
    c = repo.contracts
    if not c.path.is_file():
        return "(no CONTRACTS file)"
    text = c.path.read_text(encoding="utf-8")
    refs = [r.split("#", 1)[-1] for r in t.contracts]
    if not refs:
        return "This ticket cites no contract. It must not add or change any route, table or event."
    # Keep every level-2 section that mentions one of the refs, plus the shared preamble.
    chunks = re.split(r"(?m)^(?=## )", text)
    keep = [chunks[0]] if chunks and not chunks[0].startswith("## ") else []
    keys = set(refs) | {r.split(" ", 1)[-1] for r in refs}
    always = ("convention", "error", "auth", "envelope")
    for ch in chunks:
        heading = ch.splitlines()[0].lower() if ch else ""
        if ch.startswith("## ") and (any(k in ch for k in keys) or any(a in heading for a in always)):
            keep.append(ch)
    body = "\n".join(k.rstrip() for k in keep).strip()
    return f"Cited: {', '.join('`' + r + '`' for r in refs)}\n\nExcerpt of {cfg.rel(c.path)}:\n\n{body}"


def shared_module_rows(cfg: Config, plan: Path) -> list[tuple[str, str, str]]:
    """(module path, owner ticket, exposes) from a plan's '## Shared modules' table."""
    if not plan.is_file():
        return []
    _, body, _ = fm.split(plan.read_text(encoding="utf-8"))
    m = re.search(r"^## Shared modules\s*$(.*?)(?=^## |\Z)", body, re.M | re.S)
    rows = []
    for line in (m.group(1) if m else "").splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        path = re.fullmatch(r"`([^`]+)`", cells[0]) if len(cells) >= 2 else None
        if path:
            rows.append((path.group(1), cells[1], cells[2] if len(cells) > 2 else ""))
    return rows


def _shared_modules(cfg: Config, t: Ticket) -> str:
    """The plan's shared modules, marked with whether they exist yet and whether this
    ticket owns them, so the builder imports instead of copying (copies are a review finding)."""
    rows = shared_module_rows(cfg, cfg.root / str(t.data.get("source_plan", "")))
    if not rows:
        return ""
    out = ["| Module | Owner | Exposes | State |", "|---|---|---|---|"]
    for path, owner, exposes in rows:
        if owner == t.id:
            state = "**yours to create/extend**"
        elif (cfg.root / path).exists():
            state = "exists: import it"
        else:
            state = f"not built yet: if you need it, stop (it belongs to {owner})"
        out.append(f"| `{path}` | {owner} | {exposes} | {state} |")
    return "\n".join(out)


def _design_context(cfg: Config, repo: Repo, t: Ticket) -> list[str]:
    """Page state tables for the pages this ticket owns, plus the design tokens."""
    out = []
    pages = {r for r in t.contracts if r.startswith("/")}
    pdir = cfg.path("design") / "pages"
    for p in sorted(pdir.glob("*.md")) if pdir.is_dir() else []:
        first = (p.read_text(encoding="utf-8").splitlines() or [""])[0]
        if any(first.strip().endswith(pg) for pg in pages):
            out.append(_section(f"Page spec ({cfg.rel(p)})", _body(p)))
    tokens = cfg.path("design") / "DESIGN.md"
    if tokens.is_file():
        out.append(_section("Design tokens (design/DESIGN.md)", _body(tokens)))
    return out


def _write_set(cfg: Config, t: Ticket, play: str) -> str:
    tests = cfg.section("tests")
    if play == "build":
        lines = [f"- `{f}`" for f in t.areas] + [f"- `{g}` (shared)" for g in t.shared]
        if tests.get("unit_beside", True):
            lines.append("- unit tests beside the files above (same folder, same stem, matching the test globs)")
        lines.append(f"- `{cfg.rel(t.path)}`: amendments only (see AGENTS.md rule 7)")
        lines.append("- Areas are soft: a file outside them is flagged for the reviewer, who must accept it. Lead "
                     "artifacts, other tickets, config and the test play's files are never yours.")
    elif play == "test":
        lines = [f"- `{g}`" for g in tests.get("integration_globs", [])] or ["- (tests.integration_globs is empty: ask the lead)"]
    elif _records(cfg):
        lines = [f"- `.sdlc-run/review-{t.id}.md` (the review record; nothing in the repository)"]
    else:
        lines = [f"- `{cfg.data['paths']['reviews']}/{t.id}.md`"]
    if not _records(cfg):
        lines.append(f"- `{cfg.data['paths']['evidence']}/{t.id}.{play}.json` (written by the gate, not by you)")
    for g in cfg.section("scope").get("always_allowed", []):
        lines.append(f"- `{g}` (always allowed)")
    return "\n".join(lines)


def _dod(cfg: Config, t: Ticket, play: str) -> str:
    checks = ", ".join(cfg.section("gate")[play])
    if play == "review" and _records(cfg):
        return (f"1. Write `.sdlc-run/review-{t.id}.md`: front matter `sdlc: approval`, `ticket: {t.id}`, "
                "`commit:` the HEAD you reviewed, `verdict:`, `role: review`, `reviewer:` your agent name; then the "
                "review template from your play skill.\n"
                f"2. Run `sdlc gate review {t.id}` until it passes. Checks: {checks}.\n"
                "3. Stop. Do not merge, publish, or edit code or tests: the runner publishes the record.")
    if play == "review":
        return (f"1. Write `{cfg.data['paths']['reviews']}/{t.id}.md` from the review template in your play skill.\n"
                f"2. Run `sdlc gate review {t.id}` until it passes. Checks: {checks}.\n"
                "3. Stop. Do not merge, do not edit code or tests.")
    tags = ", ".join(f"`{x}`" for x in t.ac_tags())
    if play == "build" and t.type == "spike":
        qs = ", ".join(q for q, _ in t.questions if q)
        return (f"1. A findings file in the ticket's areas has a heading starting with each question id: {qs}.\n"
                f"2. `sdlc gate build {t.id}` passes. Checks: {', '.join(cfg.section('gate').get('spike', []))}.\n"
                "3. Change no production code and no tests.\n"
                "4. Stop. Do not change ticket status, open PRs or start another ticket: the runner does that.")
    if play == "build" and t.lane == "mechanical":
        return ("1. The diff is exactly the ticket's transforms: replaying them on the base branch gives your files "
                "byte for byte. Anything else moves the ticket to the standard lane.\n"
                f"2. `sdlc gate build {t.id}` passes. Checks: {', '.join(cfg.section('gate').get('mechanical', []))}.\n"
                "3. Read the gate output, not your memory of it. A check you did not see pass has not passed.\n"
                "4. Stop. Do not change ticket status, open PRs or start another ticket: the runner does that.")
    return (f"1. Every acceptance criterion has at least one test whose name contains its tag: {tags}.\n"
            f"2. `sdlc gate {play} {t.id}` passes. Checks: {checks}.\n"
            "3. Read the gate output, not your memory of it. A check you did not see pass has not passed.\n"
            "4. Stop. Do not change ticket status, open PRs or start another ticket: the runner does that.")


def _records(cfg: Config) -> bool:
    from . import approval

    return approval.records_mode(cfg)


def _evidence(cfg: Config, t: Ticket) -> str:
    rows, latest = [], ""
    for play in ("build", "test"):
        # Records mode keeps evidence in CI and the local run directory, never in the tree.
        p = (cfg.root / ".sdlc-run" if _records(cfg) else cfg.path("evidence")) / f"{t.id}.{play}.json"
        if not p.is_file():
            rows.append(f"### {play}\n\nNo {play} evidence at `{cfg.rel(p)}`."
                        + (" Verdict must be request_changes." if play == "build" else ""))
            continue
        ev = json.loads(p.read_text(encoding="utf-8"))
        latest = str(ev.get("commit", "")) or latest
        rows.append(f"### {play}\n\n- result: **{ev.get('result')}** at commit `{ev.get('commit')}` "
                    f"(dirty={ev.get('dirty')})")
        for c in ev.get("checks", []):
            rows.append(f"- {c['name']}: {c['status']} — {c['summary']}")
        for tag, v in ev.get("ac", {}).items():
            rows.append(f"- {tag}: {v['status']} — " + "; ".join(v["tests"][:3]))
    if latest and _records(cfg):
        # The record names the HEAD it reviewed (review-file checks that); CI proves that HEAD.
        rows.append(f"\nThe latest local evidence is for `{latest}`. The record's `commit:` is the HEAD you "
                    "reviewed (`git rev-parse HEAD`), even where the two differ.")
    elif latest:
        rows.append(f"\nSet `commit: {latest}` in the review frontmatter (the latest proven commit).")
    try:
        changed = gitutil.changed_files(cfg.root, cfg.section("vcs").get("base", "main"))
        rows.append("\n### Files this ticket changed (open every one)\n\n" + "\n".join(f"- `{f}`" for f in changed))
    except gitutil.GitError:
        pass
    return "\n".join(rows)


def _inventory(cfg: Config) -> str:
    lines = []
    for key in ("intent", "design", "arch", "decisions", "tickets"):
        d = cfg.path(key)
        if not d.is_dir():
            continue
        for p in sorted(d.rglob("*.md")):
            status = ""
            try:
                data, _ = fm.load(p)
                status = data.get("status", "")
            except fm.ParseError:
                status = "unparseable"
            lines.append(f"- `{cfg.rel(p)}`" + (f" — {status}" if status else ""))
    return "\n".join(lines) or "(none yet)"


def _body(p: Path) -> str:
    _, body, _ = fm.split(p.read_text(encoding="utf-8"))
    return body.strip()


def _section(title: str, body: str) -> str:
    return f"## {title}\n\n{body.strip()}\n"


def write(cfg: Config, play: str, ticket_id: str | None, text: str) -> Path:
    d = cfg.root / ".sdlc-run" / "prompts"
    d.mkdir(parents=True, exist_ok=True)
    p = d / (f"{play}-{ticket_id}.md" if ticket_id else f"{play}.md")
    p.write_text(text, encoding="utf-8")
    return p
