"""`sdlc prompt <play> [ticket]`: assemble the exact context a play needs.

Every agent gets the same bytes for the same inputs: the play skill, the ticket,
the cited requirements and contract sections, the skills the ticket lists, the
write set, and the definition of done. Nothing is left for the agent to go find.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from . import fm, skills
from .artifacts import Repo, Ticket
from .config import KIT_ROOT, Config

TICKET_PLAYS = ("build", "test", "review")
LEAD_PLAYS = {
    "intent": ("templates/intent.md",),
    "design": ("templates/spec.md", "templates/page.md"),
    "architect": ("templates/plan.md", "templates/CONTRACTS.md", "templates/adr.md"),
    "ticketize": ("templates/ticket.md",),
    "observe": ("templates/incident.md", "templates/intent.md"),
    "research": (),
}


def render(cfg: Config, play: str, ticket_id: str | None = None, feedback: str = "",
           extra: str = "") -> str:
    repo = Repo(cfg)
    parts: list[str] = []
    title = f"{play.upper()} {ticket_id or ''}".strip()
    parts.append(f"# sdlc play: {title}\n\n<!-- generated by `sdlc prompt`; regenerate, do not edit -->\n")
    parts.append(_section("Operating rules", _body(KIT_ROOT / "AGENTS.md")))
    parts.append(_section(f"Play skill: {play}", _body(KIT_ROOT / "skills" / play / "SKILL.md")))
    if play in TICKET_PLAYS:
        if not ticket_id:
            raise SystemExit(f"{play} needs a ticket id")
        t = repo.ticket(ticket_id)
        parts.extend(_ticket_context(cfg, repo, t, play))
    elif play in LEAD_PLAYS:
        for tpl in LEAD_PLAYS[play]:
            p = KIT_ROOT / tpl
            if p.is_file():
                parts.append(_section(f"Template: {tpl}", "```markdown\n" + p.read_text(encoding="utf-8").rstrip() + "\n```"))
        parts.append(_section("Upstream artifacts in this repo", _inventory(cfg)))
    else:
        raise SystemExit(f"unknown play {play!r}")
    if extra:
        parts.append(_section("Lead instructions for this run", extra))
    if feedback:
        parts.append(_section("The previous attempt failed the gate. Fix exactly this", feedback))
    return "\n".join(parts).rstrip() + "\n"


def _ticket_context(cfg: Config, repo: Repo, t: Ticket, play: str) -> list[str]:
    out = [_section(f"Ticket {t.id} ({cfg.rel(t.path)})", "```markdown\n" + t.path.read_text(encoding="utf-8").rstrip() + "\n```")]
    reqs = repo.requirements()
    lines = [f"- **{r}** {reqs[r].text}" if r in reqs else f"- **{r}** (not found in any spec)" for r in t.requirements]
    if lines:
        out.append(_section("Requirements this ticket serves", "\n".join(lines)))
    out.append(_section("Contracts this ticket must honour", _contract_excerpt(cfg, repo, t)))
    for s in t.skills:
        if s == play:
            continue
        p = skills.resolve(cfg, s)
        if p is not None:
            out.append(_section(f"Skill: {s}", _body(p)))
    out.append(_section("Write set (the gate rejects anything else)", _write_set(cfg, t, play)))
    if play == "review":
        out.append(_section("Build evidence", _evidence(cfg, t)))
    out.append(_section("Definition of done", _dod(cfg, t, play)))
    return out


def _contract_excerpt(cfg: Config, repo: Repo, t: Ticket) -> str:
    c = repo.contracts
    if not c.path.is_file():
        return "(no CONTRACTS file)"
    text = c.path.read_text(encoding="utf-8")
    refs = [r.split("#", 1)[-1] for r in t.contracts]
    if not refs:
        return "This ticket cites no contract. It must not add or change any route, table or event."
    # Keep every level-2 section that mentions one of the refs, plus the shared preamble.
    chunks = re.split(r"(?m)^(?=## )", text)
    keep = [chunks[0]] if chunks and not chunks[0].startswith("## ") else []
    keys = set(refs) | {r.split(" ", 1)[-1] for r in refs}
    for ch in chunks:
        if ch.startswith("## ") and any(k in ch for k in keys):
            keep.append(ch)
    body = "\n".join(k.rstrip() for k in keep).strip()
    return f"Cited: {', '.join('`' + r + '`' for r in refs)}\n\nExcerpt of {cfg.rel(c.path)}:\n\n{body}"


def _write_set(cfg: Config, t: Ticket, play: str) -> str:
    tests = cfg.section("tests")
    if play == "build":
        lines = [f"- `{f}`" for f in t.files] + [f"- `{g}` (shared)" for g in t.shared]
        if tests.get("unit_beside", True):
            lines.append("- unit tests beside the files above (same folder, same stem, matching the test globs)")
    elif play == "test":
        lines = [f"- `{g}`" for g in tests.get("integration_globs", [])] or ["- (tests.integration_globs is empty: ask the lead)"]
    else:
        lines = [f"- `{cfg.data['paths']['reviews']}/{t.id}.md`"]
    lines.append(f"- `{cfg.data['paths']['evidence']}/{t.id}.{play}.json` (written by the gate, not by you)")
    for g in cfg.section("scope").get("always_allowed", []):
        lines.append(f"- `{g}` (always allowed)")
    return "\n".join(lines)


def _dod(cfg: Config, t: Ticket, play: str) -> str:
    checks = ", ".join(cfg.section("gate")[play])
    if play == "review":
        return (f"1. Write `{cfg.data['paths']['reviews']}/{t.id}.md` from the review template in your play skill.\n"
                f"2. Run `sdlc gate review {t.id}` until it passes. Checks: {checks}.\n"
                "3. Stop. Do not merge, do not edit code or tests.")
    tags = ", ".join(f"`{x}`" for x in t.ac_tags())
    return (f"1. Every acceptance criterion has at least one test whose name contains its tag: {tags}.\n"
            f"2. `sdlc gate {play} {t.id}` passes. Checks: {checks}.\n"
            "3. Read the gate output, not your memory of it. A check you did not see pass has not passed.\n"
            "4. Stop. Do not change ticket status, open PRs or start another ticket: the runner does that.")


def _evidence(cfg: Config, t: Ticket) -> str:
    p = cfg.path("evidence") / f"{t.id}.build.json"
    if not p.is_file():
        return f"No build evidence at {cfg.rel(p)}. Verdict must be request_changes."
    ev = json.loads(p.read_text(encoding="utf-8"))
    rows = [f"- result: **{ev.get('result')}** at commit `{str(ev.get('commit'))[:12]}` (dirty={ev.get('dirty')})"]
    for c in ev.get("checks", []):
        rows.append(f"- {c['name']}: {c['status']} — {c['summary']}")
    for tag, v in ev.get("ac", {}).items():
        rows.append(f"- {tag}: {v['status']} — " + "; ".join(v["tests"][:3]))
    return "\n".join(rows)


def _inventory(cfg: Config) -> str:
    lines = []
    for key in ("intent", "design", "arch", "decisions", "tickets"):
        d = cfg.path(key)
        if not d.is_dir():
            continue
        for p in sorted(d.rglob("*.md")):
            status = ""
            try:
                data, _ = fm.load(p)
                status = data.get("status", "")
            except fm.ParseError:
                status = "unparseable"
            lines.append(f"- `{cfg.rel(p)}`" + (f" — {status}" if status else ""))
    return "\n".join(lines) or "(none yet)"


def _body(p: Path) -> str:
    _, body, _ = fm.split(p.read_text(encoding="utf-8"))
    return body.strip()


def _section(title: str, body: str) -> str:
    return f"## {title}\n\n{body.strip()}\n"


def write(cfg: Config, play: str, ticket_id: str | None, text: str) -> Path:
    d = cfg.root / ".sdlc-run" / "prompts"
    d.mkdir(parents=True, exist_ok=True)
    p = d / (f"{play}-{ticket_id}.md" if ticket_id else f"{play}.md")
    p.write_text(text, encoding="utf-8")
    return p
